#!/bin/bash
# Front-end script to duplicity to send backups to my amazon s3 buckets,
# and fire off twitter status updates.
# written by Jeff Fritz jefffritz @gmail.com
 
set -e # Exit if anything returns a bad return value.
set -u # Exit if we attempt to use an uninitialized variable
 
# Important env variables:
# - PASSPHRASE = gnupg passphrase for encrypting backups
# - AWS_ACCESS_KEY_ID = amazon s3 access key
# - AWS_SECRET_ACCESS_KEY = amazon s3 secret key
export PASSPHRASE='AKPPpfYd-8TyoB3se44g9Ajw9'
export AWS_ACCESS_KEY_ID='AKIAJKBFJDZDOTRXWUHQ'
export AWS_SECRET_ACCESS_KEY='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'
 
# Duplicity location
DUPLICITY='/usr/bin/duplicity'
V_LEVEL='debug'
 
# Log preferences 
LOG_BASE='/var/log/backup/backup'
LOG_TIME=`date +%F_%H%M`
LOG_NAME="${LOG_BASE}_${LOG_TIME}.log"
TEE='/usr/bin/tee -a'
 
# Twitter status script location
TWITTER_SCRIPT='/home/jeff/backup-scripts/send-twitter-status.pl'
 
# Base URL for destination S3 buckets
DEST_URL_BASE='s3://s3.amazonaws.com/fs-bak'
 
# Space-separated list of fully-qualified directories to back up.
# Any directory /foo/bar/baz to be backed up must ahve a corresponding bucket
# in S3 at "${DEST_URL_BASE}-foo-bar-baz"
# BACKUP_DIRS='/home/jeff /media/Master/Archive /media/Master/Main /media/Master/Music'
# BACKUP_DIRS='/home/jeff /media/Master/Main/Pictures'
BACKUP_DIRS='/media/Master/Main/Pictures'
 
# This should be 'full' or 'incremental'. If omitted, duplicity will
# do a full if the directory has never been backed up at the destination;
# otherwise it will perform an incremental.
BACKUP_TYPE=$1
 
# ---------------------- User serviceable parts stop here! ------------------------
 
touch $LOG_NAME
for i in $BACKUP_DIRS
do
    SRC=$i
    DEST_BUCKET=`echo $i | tr '/' '-'`
    DEST="${DEST_URL_BASE}${DEST_BUCKET}"
    echo "-----------------------" | $TEE $LOG_NAME
    echo "Starting backup;" | $TEE $LOG_NAME
    echo " type   = $BACKUP_TYPE" | $TEE $LOG_NAME
    echo " source = $SRC" | $TEE $LOG_NAME
    echo " dest   = $DEST" | $TEE $LOG_NAME
    echo " cmd    = $DUPLICITY $BACKUP_TYPE --verbosity $V_LEVEL $SRC $DEST >> $LOG_NAME 2>&1" | $TEE $LOG_NAME
 
    # Do the backup and log it
    echo "Executing. Output from Duplicity: " | $TEE $LOG_NAME
    $DUPLICITY $BACKUP_TYPE --verbosity notice $SRC $DEST >> $LOG_NAME 2>&1
    echo " ... complete. " | $TEE $LOG_NAME
    echo "-----------------------" | $TEE $LOG_NAME
 
    echo "Sending to twitter;" | $TEE $LOG_NAME
    # Send a twitter status.
    $TWITTER_SCRIPT $LOG_NAME | $TEE $LOG_NAME
    echo " ... complete." | $TEE $LOG_NAME
done

