#!/bin/bash
# Front-end script to duplicity to clean up rsync.net backups
# written by Jeff Fritz jefffritz@gmail.com

# NOTE This should be run first, then the duplicity full|inc command.
# See http://www.rsync.net/resources/howto/duplicity.html
 
set -e # Exit if anything returns a bad return value.
set -u # Exit if we attempt to use an uninitialized variable
 
# Custom string, if any, for logs
LOG_BASENAME="backup-cleanup"

# Bring in configuration
APP_PATH=`dirname $0`
source "$APP_PATH/backups.conf"
 
# ---------------------- User serviceable parts stop here! ------------------------
 
touch $LOG_NAME
echo "Backup log at ${LOG_TIME} - ${LOG_NAME}"
echo "Doing some clean up..."

for i in $BACKUP_DIRS
do
    DEST_BUCKET=`echo ${i:1} | tr '/' '-'`
    DEST_URL_BASE="${DESTINATION_PATH}/${DEST_BUCKET}"
    DEST="${DEST_URL_BASE}"
    echo "---------- cleanup: ${DEST_BUCKET}-------------" | $TEE $LOG_NAME
    echo "$DUPLICITY cleanup $DEST --verbosity notice --force >> $LOG_NAME 2>&1" | $TEE $LOG_NAME
    $DUPLICITY cleanup $DEST --verbosity notice --force >> $LOG_NAME 2>&1

    echo "---------- remove-older-than 30D: ${DEST_BUCKET}-------------" | $TEE $LOG_NAME
    echo "$DUPLICITY remove-older-than 30D $DEST --verbosity notice --force >> $LOG_NAME 2>&1" | $TEE $LOG_NAME
    $DUPLICITY remove-older-than 30D $DEST --verbosity notice --force >> $LOG_NAME 2>&1
done
