#!/bin/bash
# Front-end script to duplicity to send backups to rsync.net
# written by Jeff Fritz jefffritz@gmail.com
 
set -e # Exit if anything returns a bad return value.
set -u # Exit if we attempt to use an uninitialized variable
 
# Custom string, if any, for logs
LOG_BASENAME="backup"

# Bring in configuration
source backups.conf
 
# ---------------------- User serviceable parts stop here! ------------------------
 
touch $LOG_NAME
echo "Backup log at ${LOG_TIME} - ${LOG_NAME}"
echo "Backing up points: $BACKUP_DIRS"

for i in $BACKUP_DIRS
do
    SRC=$i
    DEST_BUCKET=`echo ${i:1} | tr '/' '-'`
    DEST_URL_BASE="${RSYNCNET_URL}/${DEST_BUCKET}"
    DEST="${DEST_URL_BASE}"
    echo "------------${DEST_BUCKET}-----------" | $TEE $LOG_NAME
    echo "Starting ${BACKUP_TYPE} backup..." | $TEE $LOG_NAME
    echo "Source $SRC" | $TEE $LOG_NAME
    echo "Destination $DEST" | $TEE $LOG_NAME
    echo "$DUPLICITY $BACKUP_TYPE --verbosity notice --archive-dir="${ARCHIVE_DIR}" --encrypt-key=\"$KEY_ID\" $SRC $DEST >> $LOG_NAME 2>&1" | $TEE $LOG_NAME
    $DUPLICITY $BACKUP_TYPE --verbosity notice --archive-dir="${ARCHIVE_DIR}" --encrypt-key="$KEY_ID" $SRC $DEST >> $LOG_NAME 2>&1
done
