#!/bin/bash
 
# Quick stupid script to archive all un-archived logs in the backup logs directory.
# written by Jeff Fritz jefffritz @gmail.com
# This script is meant to be run every 30 days
 
source backups.conf
 
$TAR_CMD $LOG_DIR/$ARCHIVE_NAME $LOG_DIR/$FILES_TO_ARCHIVE
 
# Cleanup logs that we archived.
$RM_CMD $LOG_DIR/$FILES_TO_ARCHIVE
